apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  labels:
    app: order-svc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
    spec:
      containers:
        - name: order-svc
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  labels:
    app: order-svc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '{{ .Values.service.port }}'
spec:
  selector:
    app: order-svc
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
